// This file is generated by kconfig_compiler from libkcddb.kcfg.
// All changes you do to this file will be lost.
#ifndef CONFIGBASE_H
#define CONFIGBASE_H

#include <libkcddb/kcddb_export.h>

#include <kglobal.h>
#include <kconfigskeleton.h>
#include <kdebug.h>

#include <QtCore/QDir>
class ConfigBasePrivate;

class KCDDB_EXPORT ConfigBase : public KConfigSkeleton
{
  public:
    class EnumFreedbLookupTransport
    {
      public:
      enum type { CDDBP, HTTP, COUNT };
    };
    class EnumFreedbSubmitTransport
    {
      public:
      enum type { HTTP, SMTP, COUNT };
    };

    ConfigBase( );
    ~ConfigBase();

    /**
      Set hostname
    */
    void setHostname( const QString & v );

    /**
      Get hostname
    */
    QString hostname() const;

    /**
      Set port
    */
    void setPort( int v );

    /**
      Get port
    */
    int port() const;

    /**
      Set MusicBrainzLookupEnabled
    */
    void setMusicBrainzLookupEnabled( bool v );

    /**
      Get MusicBrainzLookupEnabled
    */
    bool musicBrainzLookupEnabled() const;

    /**
      Set FreedbLookupEnabled
    */
    void setFreedbLookupEnabled( bool v );

    /**
      Get FreedbLookupEnabled
    */
    bool freedbLookupEnabled() const;

    /**
      Set CacheLookupEnabled
    */
    void setCacheLookupEnabled( bool v );

    /**
      Get CacheLookupEnabled
    */
    bool cacheLookupEnabled() const;

    /**
      Set FreedbLookupTransport
    */
    void setFreedbLookupTransport( int v );

    /**
      Get FreedbLookupTransport
    */
    int freedbLookupTransport() const;

    /**
      Set cacheLocations
    */
    void setCacheLocations( const QStringList & v );

    /**
      Get cacheLocations
    */
    QStringList cacheLocations() const;

    /**
      Set FreedbSubmitTransport
    */
    void setFreedbSubmitTransport( int v );

    /**
      Get FreedbSubmitTransport
    */
    int freedbSubmitTransport() const;

    /**
      Set emailAddress
    */
    void setEmailAddress( const QString & v );

    /**
      Get emailAddress
    */
    QString emailAddress() const;

    /**
      Set httpSubmitServer
    */
    void setHttpSubmitServer( const QString & v );

    /**
      Get httpSubmitServer
    */
    QString httpSubmitServer() const;

    /**
      Set httpSubmitPort
    */
    void setHttpSubmitPort( int v );

    /**
      Get httpSubmitPort
    */
    int httpSubmitPort() const;

    /**
      Set smtpPort
    */
    void setSmtpPort( int v );

    /**
      Get smtpPort
    */
    int smtpPort() const;

    /**
      Set smtpUsername
    */
    void setSmtpUsername( const QString & v );

    /**
      Get smtpUsername
    */
    QString smtpUsername() const;

    /**
      Set useGlobalEmail
    */
    void setUseGlobalEmail( bool v );

    /**
      Get useGlobalEmail
    */
    bool useGlobalEmail() const;

    /**
      Set replyTo
    */
    void setReplyTo( const QString & v );

    /**
      Get replyTo
    */
    QString replyTo() const;

    /**
      Set smtpHostname
    */
    void setSmtpHostname( const QString & v );

    /**
      Get smtpHostname
    */
    QString smtpHostname() const;

    /**
      Set submitAddress
    */
    void setSubmitAddress( const QString & v );

    /**
      Get submitAddress
    */
    QString submitAddress() const;

  protected:
  private:
    ConfigBasePrivate *d;
};

#endif

